handoff_hosts:
    managment_assistant:
      title: "HR Assistant"
      url: "http://localhost:3002/webChat"
    ## you can add more handoff hosts to this list e.g.
    HR_assistant:
      title: "Manager Assistant"
      url: "http://localhost:4200"
    
